import {NgModule} from '@angular/core';
import {
  MatAutocompleteModule,
  MatSidenavModule, 
  MatToolbarModule, 
  MatIconModule, 
  MatCheckboxModule,
  MatButtonModule, 
  MatButtonToggleModule,
  MatFormFieldModule,
  MatDialogModule,
  MatMenuModule,
  MatListModule,
  MatTabsModule,
  MatInputModule,
  MatSelectModule,
  MatCardModule,
  MatTableModule,
  MatPaginatorModule,
  MatSortModule,
  MatTooltipModule,
  MatGridListModule,
  MatExpansionModule,
  MatSnackBarModule
} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [MatAutocompleteModule,
    MatSidenavModule, 
    MatToolbarModule, 
    MatIconModule, 
    MatCheckboxModule,
    MatButtonModule, 
    MatButtonToggleModule,
    MatFormFieldModule,
    MatDialogModule,
    MatMenuModule,
    MatListModule,
    MatTabsModule,
    MatInputModule,
    MatSelectModule,
    MatCardModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatTooltipModule,
    MatGridListModule,
    MatExpansionModule,
    MatSnackBarModule],
  exports: [MatAutocompleteModule,
    MatSidenavModule, 
    MatToolbarModule, 
    MatIconModule, 
    MatCheckboxModule,
    MatButtonModule, 
    MatButtonToggleModule,
    MatFormFieldModule,
    MatDialogModule,
    MatMenuModule,
    MatListModule,
    MatTabsModule,
    MatInputModule,
    MatSelectModule,
    MatCardModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatTooltipModule,
    MatGridListModule,
    MatExpansionModule,
    MatSnackBarModule]
})
export class CustomMaterial {
}
